# -*- coding: utf-8 -*-
"""API_twitter

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1upp1LidXF-dd5jlxDv-_utfL2V9Wb6Px
"""

from cap_tweety import Tweety
import pandas as pd 


chave_consumidor = 'QATlfhbqCZ8Ju3Ld65AekgHHd'
segredo_consumidor = '1PbTijNG5Hwldcmi10X7QVPJgo8AjMIYV1Pi0Z8mDiAuOxAi6c'
token_acesso = '1425940783643910144-owtV5USsngk3lOmc9aubFgEL3dj6sB'
token_acesso_segredo = 'jiiVK3ZOSFPhuBvRySbmv0VDXFtkW7IMEdh6hGjkhFVOx'


analise = Tweety(chave_consumidor, segredo_consumidor, 
token_acesso, token_acesso_segredo)

analise.tweets(count = 300,dia = 1)    #selecione a quantidade de tweets por palavras relacionadas e pode selecinar os dias que quer executar