# -*- coding: utf-8 -*-
"""Api_Dashboard

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F-CbYUmesflXDeU-7Go32pQCw6qRtUEs
"""

from dashboard import dashb
import pandas as pd 


if __name__ == '__main__':
    dash = dashb(48,2021)    # selecionar a semana do ano e o ano 
    app = dash.app
    app.run_server(debug=True)
